services:
  redis-prod:
    extends:
      file: compose.yml
      service: redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  selenium-prod:
    extends:
      file: compose.yml
      service: selenium
  api-prod:
    extends:
      file: compose.yml
      service: api
    ports:
      - 80:8000
    env_file:
      - .env.prod
    environment:
      - REDIS_HOST=redis-prod
      - SELENIUM_HOST=selenium-prod
    depends_on:
      - redis-prod
      - selenium-prod