services:
  redis:
    container_name: redis-db
    image: "redis/redis-stack:latest"
    ports:
      - 6379:6379
      - 8001:8001
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  selenium:
    image: "selenium/standalone-chromium:latest"
    ports:
      - 4444:4444
  api:
    container_name: flask
    build:
      context: .
    restart: on-failure:3
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - SELENIUM_HOST=selenium
    ports:
      - 8000:8000
    depends_on:
      - redis
      - selenium